# Generated by Django 4.0.5 on 2022-06-15 11:56

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=500)),
                ('Text', models.TextField()),
                ('Creation_Datetime', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('Update_Datetime', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('Author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Word', models.CharField(max_length=100)),
                ('Count_Doc', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TrendingDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Clicks_quarter1', models.BigIntegerField()),
                ('Clicks_quarter2', models.BigIntegerField()),
                ('Clicks_quarter3', models.BigIntegerField()),
                ('Clicks_quarter4', models.BigIntegerField()),
                ('Clicks_total', models.BigIntegerField()),
                ('Doc', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='djangoApp.document')),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateandTime', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('SeachQuery', models.CharField(max_length=500)),
                ('Doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoApp.document')),
                ('Read_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
