# Generated by Django 4.0.5 on 2022-06-20 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoApp', '0003_alter_document_creation_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
