# Generated by Django 4.0.5 on 2022-06-20 02:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('djangoApp', '0004_alter_keyword_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='SeachQuery',
            new_name='SearchQuery',
        ),
        migrations.AlterField(
            model_name='history',
            name='Read_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
