# Generated by Django 4.0.5 on 2022-06-22 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoApp', '0005_rename_seachquery_history_searchquery_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trendingdocument',
            name='Clicks_quarter1',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='trendingdocument',
            name='Clicks_quarter2',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='trendingdocument',
            name='Clicks_quarter3',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='trendingdocument',
            name='Clicks_quarter4',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='trendingdocument',
            name='Clicks_total',
            field=models.BigIntegerField(default=0),
        ),
    ]
